version: '3.8'
services:
  traefik:
    image: traefik:2.1
    restart: always
    ports:
      - '80:85'
      - '443:443'
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootroot'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'

  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.my-app.rule=Host(`prod.emptydev.fr`)'
      - 'traefik.http.routers.my-app.tls=true'
      - 'traefik.http.routers.my-app.tls.certresolver=lets-encrypt'
    ports:
      - "85:8080"
    depends_on:
      - db

  node:
    image: node:12-alpine
    command: sh -c "yarn install && yarn encore dev --watch"
    volumes:
      - .:/app:cached
    working_dir: /app
